ALTER TABLE users ADD COLUMN bio TEXT;
ALTER TABLE users ADD COLUMN instagram_url VARCHAR(255);
ALTER TABLE users ADD COLUMN twitter_url VARCHAR(255);
ALTER TABLE users ADD COLUMN youtube_url VARCHAR(255);
ALTER TABLE users ADD COLUMN spotify_url VARCHAR(255);
