ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE genres ALTER COLUMN id DROP DEFAULT;
ALTER TABLE specs ALTER COLUMN id DROP DEFAULT;
ALTER TABLE license_options ALTER COLUMN id DROP DEFAULT;
ALTER TABLE orders ALTER COLUMN id DROP DEFAULT;
ALTER TABLE payments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE licenses ALTER COLUMN id DROP DEFAULT;
ALTER TABLE analytics_events ALTER COLUMN id DROP DEFAULT;
