//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for LicenseOptionType.
const (
	Basic     LicenseOptionType = "Basic"
	Premium   LicenseOptionType = "Premium"
	Trackout  LicenseOptionType = "Trackout"
	Unlimited LicenseOptionType = "Unlimited"
)

// Valid indicates whether the value is a known member of the LicenseOptionType enum.
func (e LicenseOptionType) Valid() bool {
	switch e {
	case Basic:
		return true
	case Premium:
		return true
	case Trackout:
		return true
	case Unlimited:
		return true
	default:
		return false
	}
}

// Defines values for SpecCategory.
const (
	Beat   SpecCategory = "beat"
	Sample SpecCategory = "sample"
)

// Valid indicates whether the value is a known member of the SpecCategory enum.
func (e SpecCategory) Valid() bool {
	switch e {
	case Beat:
		return true
	case Sample:
		return true
	default:
		return false
	}
}

// Defines values for SpecProcessingStatus.
const (
	Completed  SpecProcessingStatus = "completed"
	Failed     SpecProcessingStatus = "failed"
	Pending    SpecProcessingStatus = "pending"
	Processing SpecProcessingStatus = "processing"
)

// Valid indicates whether the value is a known member of the SpecProcessingStatus enum.
func (e SpecProcessingStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Processing:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`

	// Error Example: invalid request body
	Error string `json:"error"`
}

// FavoriteItem defines model for FavoriteItem.
type FavoriteItem struct {
	FavoritedAt time.Time `json:"favorited_at"`
	Spec        Spec      `json:"spec"`
}

// FavoritePage defines model for FavoritePage.
type FavoritePage struct {
	HasMore bool           `json:"has_more"`
	Items   []FavoriteItem `json:"items"`

	// NextCursor Present when another page is available.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Genre defines model for Genre.
type Genre struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
}

// LicenseOption defines model for LicenseOption.
type LicenseOption struct {
	CreatedAt         time.Time          `json:"created_at"`
	DisplayPriceMoney Money              `json:"display_price_money"`
	Features          []string           `json:"features"`
	FileTypes         []string           `json:"file_types"`
	Id                openapi_types.UUID `json:"id"`
	Name              string             `json:"name"`
	Price             float64            `json:"price"`
	PriceMoney        Money              `json:"price_money"`
	SpecId            openapi_types.UUID `json:"spec_id"`
	Type              LicenseOptionType  `json:"type"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

// LicenseOptionType defines model for LicenseOption.Type.
type LicenseOptionType string

// Money defines model for Money.
type Money struct {
	// AmountMajor Decimal amount in the currency's major unit
	AmountMajor float64 `json:"amount_major"`

	// AmountMinor Amount in the currency's smallest unit
	AmountMinor int64 `json:"amount_minor"`

	// Currency Example: INR
	Currency string `json:"currency"`
}

// PlainTextError Error body written by net/http's http.Error. Some handlers currently put JSON-looking text in this plain-text body.
//
// Example: invalid request body
type PlainTextError = string

// PublicAnalytics defines model for PublicAnalytics.
type PublicAnalytics struct {
	FavoriteCount      int  `json:"favorite_count"`
	IsFavorited        bool `json:"is_favorited"`
	PlayCount          int  `json:"play_count"`
	TotalDownloadCount int  `json:"total_download_count"`
}

// Spec defines model for Spec.
type Spec struct {
	Analytics         *PublicAnalytics `json:"analytics,omitempty"`
	Bpm               int              `json:"bpm"`
	Category          SpecCategory     `json:"category"`
	CreatedAt         time.Time        `json:"created_at"`
	Description       string           `json:"description"`
	DisplayPriceMoney Money            `json:"display_price_money"`

	// Duration Seconds
	Duration         int                  `json:"duration"`
	FreeMp3Enabled   bool                 `json:"free_mp3_enabled"`
	Genres           *[]Genre             `json:"genres,omitempty"`
	Id               openapi_types.UUID   `json:"id"`
	ImageUrl         string               `json:"image_url"`
	Instruments      *[]string            `json:"instruments,omitempty"`
	Key              string               `json:"key"`
	Licenses         *[]LicenseOption     `json:"licenses,omitempty"`
	Moods            *[]string            `json:"moods,omitempty"`
	PreviewUrl       string               `json:"preview_url"`
	Price            float64              `json:"price"`
	PriceMoney       Money                `json:"price_money"`
	ProcessingStatus SpecProcessingStatus `json:"processing_status"`
	ProducerId       openapi_types.UUID   `json:"producer_id"`
	ProducerName     string               `json:"producer_name"`
	ShortCode        *string              `json:"short_code,omitempty"`
	Slug             *string              `json:"slug,omitempty"`
	Tags             *[]string            `json:"tags,omitempty"`
	Title            string               `json:"title"`
	Type             string               `json:"type"`
	UpdatedAt        time.Time            `json:"updated_at"`
	WaveformPeaks    *[]int64             `json:"waveform_peaks,omitempty"`
}

// SpecCategory defines model for Spec.Category.
type SpecCategory string

// SpecProcessingStatus defines model for Spec.ProcessingStatus.
type SpecProcessingStatus string

// AssetID defines model for AssetID.
type AssetID = openapi_types.UUID

// CloudflareCountry Example: IN
type CloudflareCountry = string

// CountryCode Example: IN
type CountryCode = string

// ID defines model for ID.
type ID = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListMyFavoritesParams defines parameters for ListMyFavorites.
type ListMyFavoritesParams struct {
	// Limit Maximum number of favorites to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned by the previous response.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// CFIPCountry Cloudflare two-letter country code. IN selects INR display prices; every other value selects USD.
	CFIPCountry *CloudflareCountry `json:"CF-IPCountry,omitempty"`

	// XCountryCode Fallback country code when CF-IPCountry is absent. IN selects INR display prices; every other value selects USD.
	XCountryCode *CountryCode `json:"X-Country-Code,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListMyFavorites List the authenticated user's favorited beats
	// (GET /me/favorites)
	ListMyFavorites(w http.ResponseWriter, r *http.Request, params ListMyFavoritesParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListMyFavorites operation middleware
func (siw *ServerInterfaceWrapper) ListMyFavorites(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMyFavoritesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "CF-IPCountry" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("CF-IPCountry")]; found {
		var CFIPCountry CloudflareCountry
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "CF-IPCountry", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "CF-IPCountry", valueList[0], &CFIPCountry, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "CF-IPCountry", Err: err})
			return
		}

		params.CFIPCountry = &CFIPCountry

	}

	// ------------- Optional header parameter "X-Country-Code" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Country-Code")]; found {
		var XCountryCode CountryCode
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Country-Code", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Country-Code", valueList[0], &XCountryCode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Country-Code", Err: err})
			return
		}

		params.XCountryCode = &XCountryCode

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMyFavorites(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me/favorites", wrapper.ListMyFavorites)

	return m
}

type BadRequestJSONResponse Error
type BadRequestTextResponse PlainTextError

type InternalErrorJSONResponse Error
type InternalErrorTextResponse PlainTextError

type UnauthorizedJSONResponse Error
type UnauthorizedTextResponse PlainTextError

type ListMyFavoritesRequestObject struct {
	Params ListMyFavoritesParams
}

type ListMyFavoritesResponseObject interface {
	VisitListMyFavoritesResponse(w http.ResponseWriter) error
}

type ListMyFavorites200JSONResponse FavoritePage

func (response ListMyFavorites200JSONResponse) VisitListMyFavoritesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyFavorites400JSONResponse struct{ BadRequestJSONResponse }

func (response ListMyFavorites400JSONResponse) VisitListMyFavoritesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyFavorites400TextResponse BadRequestTextResponse

func (response ListMyFavorites400TextResponse) VisitListMyFavoritesResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type ListMyFavorites401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListMyFavorites401JSONResponse) VisitListMyFavoritesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyFavorites401TextResponse UnauthorizedTextResponse

func (response ListMyFavorites401TextResponse) VisitListMyFavoritesResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type ListMyFavorites500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListMyFavorites500JSONResponse) VisitListMyFavoritesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyFavorites500TextResponse InternalErrorTextResponse

func (response ListMyFavorites500TextResponse) VisitListMyFavoritesResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListMyFavorites List the authenticated user's favorited beats
	// (GET /me/favorites)
	ListMyFavorites(ctx context.Context, request ListMyFavoritesRequestObject) (ListMyFavoritesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListMyFavorites operation middleware
func (sh *strictHandler) ListMyFavorites(w http.ResponseWriter, r *http.Request, params ListMyFavoritesParams) {
	var request ListMyFavoritesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyFavorites(ctx, request.(ListMyFavoritesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyFavorites")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMyFavoritesResponseObject); ok {
		if err := validResponse.VisitListMyFavoritesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FpZbxs58v8qBP9/YICgJTnH7IP2ybHHu5rNYfjALBAHSqlZkhizyQ4P2VpD331Bsm+1bDnWLDBPdpPF",
	"Yl2s+hWpB5qqLFcSpTV0/EBz0JChRR2+jo1BOzn1/3JJxzQHu6QJlZAhHVMoZhOq8YfjGhkdW+0woSZd",
	"YgZ+2VzpDCwdU+c4owm169wvNVZzuaCbTUJPhHJsLkDjiXLS6rVfxtCkmueWK79tTULsnRoItBY1SSM5",
	"SRXDIZl8IgYFptaQyacLwrjJBaxJrnmK5u8EV6jXRNklarIC4bCivr48HdIk6rdEYKhrDU/OBpPzUqym",
	"WngPWS48yeQTTWgG9x9QLuySjt8kNOOy8dWjcWR4ohhu63oGQswgvW2pR+6WKElTGsINgZlBaf8k1f89",
	"KHYaBDkPpnyMprbOF2iU0ymS6+vJ6ZCcgAWhFkQodetyAsIoAmmKuTUEiFkqbaNVlCZGuEWlQzs8Q7zt",
	"jsyuaBtPbHIlDYbYfw/sAn84NNZ/pUpalOFfyHPBU/Cyj74br8BDg+3/a5zTMf2/UX2uRnHWjH7TWulg",
	"BYv3dpQL4M9Yfe7Jr/Delmw2SceOE7kCwRnhMneWemNLi1qCiCv+KmpcS7zPMbXIiEG9Qk0wkib0WoKz",
	"S6X5f7xL/yL6fOTGcLnw4coLD3ktUNpC3rB3wc9vV7kr1ypHbXmMSIYWuDA9wZtQLJfUh7PcS8coJjPF",
	"1r0ZuD4jXwo+XysyNfuOaYilM1gpzS1OLGbB3oxxLzyI84aUcxAGk47g82Ipm4JtFQUGFgeWZ7gtV0JN",
	"julTxr/0NF0dWtsVfB7T6BwW+EyNlmCmmdLY8MVMKYEgPWNuMQtk1T+P6dAy7KaSE7SGtf+WeG+nqdMm",
	"OrgdW+cafRGIBQJkzPI5LDAUiBVwATOBwyf9HiVNasX6DPYPlFHltjFSjfBc53K2BzooU3lPvPu835fF",
	"O1qxshwUK5KmsH0qfuApSoOfC/seQtWiHk9DPZ5mSuL6qZD4GIg2CZ0jWKexHUxbO3QjZs4FTv3gM9e9",
	"1ClBw7ZhlJuJhlWky2aoK9pnWsOf5OmeQsaBB4rSZT4U3oPhKU38gcm4y2hCrzSkt8r5FHEtBc98xmjE",
	"RM3K5eyZTu8Lw1L4griKy2i0tkH6g6YRDi0ft4K6JW5fhH8sTd6ObMg83Jtm8L0vzZxiyjMQJFIRLold",
	"Ikmd1ijT9S+GhHXESe4l2MP95XZc9m13vGsbk4EQvph1d+LS/u1dvRGXFhdxp3J1F7lePOm2loxJ20IN",
	"vn1G7oCCLQXDcKjI5E5za1GS2ZpItKOltfkvhvg/w0A1JJcqQ7IEyQRqU1jDijXJnSW/X37+NPBA2QMM",
	"D1+i0bghAcYMwpDfx5eA52KDhJ67meDpsQSxtjw122FT1tppaFcaWaHhAW6mVUnuL5gh1B/hYJUFMWXq",
	"TgoFbDdlx4ENtklX0h1MO9L2+faywCWd89O00aN4sWPSTUJnedavdwoWFyq2xGUim2FENdGVffnqp4pU",
	"MzwfDlvEmNNQMm4fg0tMlWSm99zONeI0y99OUXoIsyNyFh6S7I+1IoL5+dLHM1jg1GnRpta8l1gaq11W",
	"Xq3sX4dvo3G36EQEJ/ur20YzPTtlSrFnCpdrXHG829cIfzYmyLVKMfRXU2PBOtM8KzlK5uVokvnUrfzZ",
	"8efbpwUudtT9XCvmUtT7Qo6KfjdqXSptp2lx8bMvqE2ohcUzvWS5FfgI5cMhYE5C72CFnnKaI9y2Rdyj",
	"NLeF7gNNTRd0DVwq2UiTFbbyGTWeo3Zqa57gdig/D4hVKa0nT+2GY33Rul1hfCBg6jS360sf7fG8zxA0",
	"6mNnl/XXWWni3/+4ot1bh+PU70SsukVJNFqnJTKPMoRacEmUJhrnGs1yWF7uhdQaGNfe8jiEBs8E2hOP",
	"NHpuLf95dXU+UFKsS6bEeDWVJGlYQQzaau/qvi7O1Td2xdppkLmWAXL+L3/YNyGnzlV58QNpiNRi8R+w",
	"wjVoRn6TCy4ReytbEJQcn0/IXOkALqtlvq6SDPQt2lxAisMbeSOvDZJXr47LO6dXr4hVJNdqxRkSkOFa",
	"sjIyGPLtfbAfuXFHR2/TMBz+xW9hw1wrGy62bqTHDiGEzJBcFDYL9IaARmKs0sg8mANJaut+a5noW2Hd",
	"4Y2sTkPDEMfnE5rQFWoTdX89PBoeeZOoHCXknI7p2+HR8K2PS7DLEGYjYBmXowrNjNQKtT8kdPywSapp",
	"x7gdCLVojTbKUz2oNIuPCfWQ74R6RkYPnG26bxBf+stATTKanNLN15qVM93twsgBmQdWo7rYHIzj2ljM",
	"BlrFxP2zbHd6rpqwKh+0fODscjRXeqHsIAdj7pRmzamFUosgUzUi1MI3zo2RIi7bQwYlG6xQ83l50dmZ",
	"7t8vrFgPMAMuivE0PgmMliorBVkiCFtu2Am98jMatoT4L/FWSFwF90qEDEdlqxB4L9D2PW741GtI1VSE",
	"TGNIOBgxI5dTJBQOnzV9vU2IxDvfnM25NnZ4I69iL2yUJtwQlcMP55MQI5nzLRzWWd7JdAlyEbmngnu1",
	"YpKo0s6E0TH9wI39uD6rdEi65ulcZMM9z1xGImIjal5J7lNgsX2V3X84DCW5yM/hhqX1jsRwDk5YOn5z",
	"FF6RPG86/vUoPCLFj9dJT4/XFetztERhmmap8wk+FHnlDClfd3YJWFyxPvZGlDwZMNuvmfssajwIbr52",
	"3qHeHB0d7KWjdePd81Jx1o5RXyvexe37uFZijhpvZWHJ66eXtF5yNgn9dZ992u9ZTaQUorWJkb589ZY0",
	"LsvA988h1EM8NJ5e/EkxqH/ZOpy0hNxfaPEYSb9u4om3mleJUypbpbbesZFGYAMQonfSyTBd3mZsE4Ts",
	"5WlekLha9Td+jEoc3R59YYXMYR1a3SJ9F7w1Lrix1Va+7AxcXmbj7tBLZdjiNSpbvYMynXOB5vAcRw/F",
	"LypeKvbTGaf8YccueTK0wMDCC5Vs+vggzi3Ea122vZxdCRAGvpc7DMsyoRyGm+9AX8ApgsxcKx9mhUta",
	"YyNYgQXdOzUDKbE9FWUK95gvlipC3yJWfpbVHc6WSt2aEVNMFaLeheALJUKv+vHMSbxKD/3gUpnQrWtB",
	"x3QUynBRArZ63QA8A/BSM88cZlxwuyYoWa64DOWjwBSfqy6PbuOWi5Ab43xSNswmIU3EnIR9SpRMNKYe",
	"1jdQy3HnlwRbu8T75tjeFjA68iyKQDVYd6SNH0AV1W+b7anTMBNIMicsHxiLec0xphKS8xwFl40G/7rI",
	"/Nvsrg2G9jgkwihflLti6jt/nZW3LiXD0O31QMJQ0hJSFKWOScv2IBq3bg8qtudFLdslaKtMBybaBwXP",
	"kBg3a143FQw/tZBCj5MErE1Sw+mk7aI639V+bzwgbF2ruxz1IDSYJAMJCwxG8CxD597r6mNPHuL+fhCB",
	"1OAJcHU/KLq+NmHnqqikNRYkA80G4Scm4bT/r7Dlu6O3Ty86U3rGGUP502h0898AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
